version: '2'
services:
    nginx-proxy:
        image: jwilder/nginx-proxy:latest
        container_name: nginx-proxy
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
        ports:
            - 80:80
        restart: always

    watchtower:
        image: containrrr/watchtower:latest
        container_name: watchtower
        volumes:
            - /var/run/docker.sock:/var/run/docker.soc
        restart: always

    plex:
        image: linuxserver/plex
        container_name: plex
        volumes:
            - /mnt/config/plex:/config
            - /mnt/Media/TV:/data/tvshows
            - /mnt/Media/Movies:/data/movies
        ports:
            - 32469:32469
            - 32400:32400
            - 32401:32401
            - 3005:3005
            - 8324:8324
            - 1900:1900/udp
            - 32410:32410/udp
            - 32412:32412/udp
            - 32413:32413/udp
            - 32414:32414/udp
        env_file: uidgid.env
        environment:
            - VIRTUAL_HOST=plex.jomi.wtf
            - VIRTUAL_PORT=32400
            - PLEX_CLAIM=claim-AUdEsMzA7oUaPLd_RqjF
        restart: always

    sonarr:
        image: ghcr.io/linuxserver/sonarr
        container_name: sonarr
        volumes:
            - /mnt/config/sonarr:/config
            - /etc/localtime:/etc/localtime:ro
            - /mnt/Media/TV:/tv
            - /mnt/Downloads/complete:/downloads
        ports:
            - 8989:8989
        env_file: uidgid.env
        environment:
            - VIRTUAL_HOST=sonarr.jomi.wtf
            - VIRTUAL_PORT=8989
        restart: always

    nzbhydra:
        image: linuxserver/hydra2
        container_name: nzbhydra
        volumes:
            - /mnt/config/nzbhydra:/config
            - /mnt/Downloads:/downloads
            - /etc/localtime:/etc/localtime:ro
        ports:
            - 5075:5075
        env_file: uidgid.env
        environment:
            - VIRTUAL_HOST=nzbhydra.jomi.wtf
            - VIRTUAL_PORT=5075
        restart: always

    muximux:
        image: linuxserver/muximux
        container_name: muximux
        volumes:
            - /mnt/config/muximux:/config
            - /etc/localtime:/etc/localtime:ro
        env_file: uidgid.env
        environment:
            - VIRTUAL_HOST=muximux.jomi.wtf
        restart: always

    radarr:
        image: linuxserver/radarr
        container_name: radarr
        volumes:
            - /mnt/config/radarr:/config
            - /mnt/Media/Movies:/movies
            - /mnt/Downloads/complete:/downloads
            - /etc/localtime:/etc/localtime:ro
        ports:
            - 7878:7878
        env_file: uidgid.env
        environment:
            - VIRTUAL_HOST=radarr.jomi.wtf
            - VIRTUAL_PORT=7878
        restart: always

    ombi:
        image: ghcr.io/linuxserver/ombi
        container_name: ombi
        volumes:
            - /mnt/config/ombi:/config
            - /etc/localtime:/etc/localtime:ro
        ports:
            - 3579:3579
        env_file: uidgid.env
        environment:
            - VIRTUAL_HOST=ombi.jomi.wtf
            - VIRTUAL_PORT=3579
        restart: always

    nzbget:
        image: linuxserver/nzbget
        container_name: nzbget
        volumes:
            - /mnt/config/nzbget:/config
            - /mnt/Downloads/complete:/complete
            - /mnt/Downloads:/downloads
            - /mnt/nzb_intermediate:/intermediate
        ports:
            - 6789:6789
        env_file: uidgid.env
        environment:
            - VIRTUAL_HOST=nzbget.jomi.wtf
            - VIRTUAL_PORT=6789
        restart: always

    pihole:
        image: pihole/pihole
        container_name: pihole
        volumes:
            - /mnt/config/etc-pihole/:/etc/pihole/
            - /mnt/config/etc-dnsmasq.d/:/etc/dnsmasq.d/
        ports:
            - 53:53
            - 53:53/udp
            - 67:67/udp
            - 81:80
            - 443:443
        env_file: uidgid.env
        environment:
            - TZ=America/New_York
            - WEBPASSWORD=00Broadcast
        cap_add:
            - NET_ADMIN
        restart: always
